quarkus:
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/learn
    username: postgres
    password: 123qwe
  hibernate-orm:
    database:
      generation: update
  http:
    access-log:
      enabled: true
      pattern: '%{i,Remote-Addr} - %u "%r" %s %b %Dms'
    record-request-start-time: true